import { ValueOrFunc } from './common';
import { FormItem, FormFieldInit, FormField, FormGroupInit, FormGroup, FormGroupFields, FormListingInit, FormListing, ExtraFormInfo } from './forms.interfaces';
export declare const field: <T = any>(initValue: T, options?: Partial<FormFieldInit<T>>) => FormField<T>;
export declare const group: <T = any>(fields: FormGroupFields<T>, options?: Partial<FormGroupInit<T>>) => FormGroup<T>;
export declare const listing: <T = any>(fields: FormItem<T>[], options?: Partial<FormListingInit<T>>) => FormListing<T>;
export declare const getFormItem: <T extends FormItem<any> = FormItem<any>>(item: FormItem<any>, path?: string) => T;
export declare const getFormField: <T = any>(item: FormItem<any>, path?: string) => FormField<T>;
export declare const getFormGroup: <T = any>(item: FormItem<any>, path?: string) => FormGroup<T>;
export declare const getFormListing: <T = any>(item: FormItem<any>, path?: string) => FormListing<T>;
export declare const getValue: (item: FormItem<any>, path?: string) => any;
export declare const existFormItem: (item: FormItem<any>, path: string) => boolean;
export declare const setValue: <I extends FormItem<any> = FormItem<any>>(item: I, value: any, pathToField?: string) => I;
export declare const setValueDoNotTouch: <I extends FormItem<any> = FormItem<any>>(item: I, value: any, pathToField?: string) => I;
export declare const setInput: <I extends FormItem<any> = FormItem<any>>(item: I, input: any, pathToField?: string) => I;
export declare const setInputDoNotTouch: <I extends FormItem<any> = FormItem<any>>(item: I, input: any, pathToField?: string) => I;
export declare const resetValue: <I extends FormItem<any> = FormItem<any>>(item: I, pathToField?: string, value?: any) => I;
export declare const setGroupField: <I extends FormItem<any> = FormItem<any>>(item: I, pathToGroupField: string, formItem: ValueOrFunc<FormItem<any>>) => I;
export declare const insertListingFields: <I extends FormItem<any> = FormItem<any>>(item: I, pathToListing: string, newFields: ValueOrFunc<FormField<any> | FormGroup<any> | FormListing<any> | FormItem<any>[]>, atPosition?: number) => I;
export declare const removeListingFields: <I extends FormItem<any> = FormItem<any>>(item: I, pathToListing: string, atPosition: number, count?: number) => I;
export declare const updateFormInfo: <I extends FormItem<any> = FormItem<any>>(item: I, pathToFormItem: string, updater: ValueOrFunc<Partial<ExtraFormInfo>>) => I;
export declare const getAllErrors: (item: FormItem<any>) => import("./forms.interfaces").FormError[];
export declare const setInfo: <I extends FormItem<any> = FormItem<any>>(item: I, info: any, pathToField?: string) => I;
