name: ci

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - run: corepack enable

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - run: pnpm install
      - run: pnpm lint
      - run: pnpm test:prod

  release:
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - uses: actions/checkout@v3

      - run: corepack enable

      - uses: actions/setup-node@v3
        with:
          cache: 'pnpm'
          registry-url: https://registry.npmjs.org/

      - run: pnpm install
      - run: pnpm types
      - run: pnpm build

      - run: |
          git config user.email "github-action@users.noreply.github.com"
          git config user.name "TestJG Bot"

      - run: pnpm dlx changelogen@latest --release
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}

      - run: git push --follow-tags
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - uses: actions/checkout@v3

      - run: corepack enable

      - uses: actions/setup-node@v3
        with:
          cache: 'pnpm'

      - run: pnpm install
      - run: pnpm run docs

      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './compiled/docs'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
